# Generated by Django 3.0.7 on 2023-04-10 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0011_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default="{% static 'login/image/student.jpg' %}", upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 4, 10, 11, 26, 55, 884546), verbose_name='生日'),
        ),
    ]
