# Generated by Django 3.0.7 on 2023-04-10 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0012_auto_20230410_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default="{% static 'media/student.jpg' %}", upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 4, 10, 12, 5, 16, 855329), verbose_name='生日'),
        ),
    ]
