# Generated by Django 3.0.7 on 2023-04-10 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0013_auto_20230410_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default="{% static 'media/student.jpg' %}", max_length=128, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 4, 10, 12, 21, 48, 748883), verbose_name='生日'),
        ),
    ]
