# Generated by Django 3.0.7 on 2023-04-10 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0014_auto_20230410_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 4, 10, 13, 29, 57, 363162), verbose_name='生日'),
        ),
    ]
